# Workflow that runs regression tests against our solved test bugs
name: Run Replay Regression Tests

# The jobs in this workflow are required, so they must run at all times
# * Always run on "main"
# * Always run on PRs
on:
  push:
    branches:
      - main
  pull_request:

# If triggered by a PR, it will be in the same group. However, each commit on main will be in its own unique group
concurrency:
  group: ${{ github.workflow }}-${{ (github.head_ref && github.ref) || github.run_id }}
  cancel-in-progress: true

jobs:
  check-for-regressions:
    runs-on: ubuntu-latest
    steps:
      - name: Check 10609
        uses: actions/github-script@v7
        if: always() # don't let other checks keep this from running
        with:
          github-token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: "bench-devtools-10609",
              workflow_id: "regress-check.yml",
              ref: "main",
            });
